// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: albetacom

#ifndef _ALBETACOM_UI_H
#define _ALBETACOM_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ha_alarm_keypad
void ui_ha_alarm_keypad_screen_init(void);
extern lv_obj_t * ui_ha_alarm_keypad;
extern lv_obj_t * ui_ha_alarm_label;
extern lv_obj_t * ui_Container1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label9;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label10;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_LabelCode;
extern lv_obj_t * ui____initial_actions0;


void ui_albetacom_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
