// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: albetacom

#include "ui.h"

void Button1ClickedAction(lv_event_t * e)
{
	// Your code here
	printf("HE APRETADO EL 1\n");
}

void ButtonClearClickedAction(lv_event_t * e)
{
	// Your code here
	printf("HE APRETADO EL CLEAR\n");
}

void ButtonSendClickedAction(lv_event_t * e)
{
	// Your code here
	printf("HE APRETADO EL SEND\n");
}
