// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: small

#include "../ui.h"

void ui_Alarm_keypad_screen_init(void)
{
    ui_Alarm_keypad = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Alarm_keypad, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Alarm_keypad, lv_color_hex(0x1C1C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Alarm_keypad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ha_keypad_label = lv_label_create(ui_Alarm_keypad);
    lv_obj_set_width(ui_ha_keypad_label, 316);
    lv_obj_set_height(ui_ha_keypad_label, 38);
    lv_obj_set_x(ui_ha_keypad_label, 82);
    lv_obj_set_y(ui_ha_keypad_label, 58);
    lv_label_set_text(ui_ha_keypad_label, "Alarm code");
    lv_obj_set_style_text_color(ui_ha_keypad_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ha_keypad_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ha_keypad_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ha_keypad_label, &ui_font_font0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_Alarm_keypad);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard1, 404);
    lv_obj_set_height(ui_Keyboard1, 348);
    lv_obj_set_x(ui_Keyboard1, 1);
    lv_obj_set_y(ui_Keyboard1, 41);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_Keyboard1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);


}
