// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: albetacom

#ifndef _ALBETACOM_UI_H
#define _ALBETACOM_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ha_alarm_keypad
void ui_ha_alarm_keypad_screen_init(void);
void ui_event_ha_alarm_keypad(lv_event_t * e);
extern lv_obj_t * ui_ha_alarm_keypad;
extern lv_obj_t * ui_ha_alarm_label;
extern lv_obj_t * ui_Container1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label3;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label4;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label5;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label6;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label7;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label8;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label9;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label11;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label10;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_LabelCode;
extern lv_obj_t * ui_LabelCode1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_acoff_png);    // assets/acoff.png
LV_IMG_DECLARE(ui_img_acon_png);    // assets/acon.png
LV_IMG_DECLARE(ui_img_alarmarmedaway_png);    // assets/alarmarmedaway.png
LV_IMG_DECLARE(ui_img_alarmarmedhome_png);    // assets/alarmarmedhome.png
LV_IMG_DECLARE(ui_img_alarmdisarmed_png);    // assets/alarmdisarmed.png
LV_IMG_DECLARE(ui_img_alarmwarning_png);    // assets/alarmwarning.png
LV_IMG_DECLARE(ui_img_ceilingfanoff_png);    // assets/ceilingfanoff.png
LV_IMG_DECLARE(ui_img_ceilingfanon_png);    // assets/ceilingfanon.png
LV_IMG_DECLARE(ui_img_coverclosed_png);    // assets/coverclosed.png
LV_IMG_DECLARE(ui_img_coveropen_png);    // assets/coveropen.png
LV_IMG_DECLARE(ui_img_curtainclosed_png);    // assets/curtainclosed.png
LV_IMG_DECLARE(ui_img_curtainopen_png);    // assets/curtainopen.png
LV_IMG_DECLARE(ui_img_lightoff_png);    // assets/lightoff.png
LV_IMG_DECLARE(ui_img_lighton_png);    // assets/lighton.png
LV_IMG_DECLARE(ui_img_down_png);    // assets/down.png
LV_IMG_DECLARE(ui_img_up_png);    // assets/up.png



LV_FONT_DECLARE(ui_font_font0);
LV_FONT_DECLARE(ui_font_font2);
LV_FONT_DECLARE(ui_font_font3);
LV_FONT_DECLARE(ui_font_font4);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
