// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: albetacom

#ifndef _ALBETACOM_UI_H
#define _ALBETACOM_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ha_alarm_keypad
void ui_ha_alarm_keypad_screen_init(void);
void ui_event_ha_alarm_keypad(lv_event_t * e);
extern lv_obj_t * ui_ha_alarm_keypad;
extern lv_obj_t * ui_ha_alarm_label;
extern lv_obj_t * ui_Container1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label3;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label4;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label5;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label6;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label7;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label8;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label9;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label11;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label10;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_LabelCode;
extern lv_obj_t * ui_LabelCode1;
// SCREEN: ui_ha_ev_charge
void ui_ha_ev_charge_screen_init(void);
extern lv_obj_t * ui_ha_ev_charge;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_LabelEVBattery;
extern lv_obj_t * ui_LabelEVRange;
extern lv_obj_t * ui_LabelEVStatus;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_teslamodel3_png);    // assets/teslamodel3.png
LV_IMG_DECLARE(ui_img_evcharger_png);    // assets/evcharger.png
LV_IMG_DECLARE(ui_img_919524860);    // assets/2023-11-13-20-02-12.png
LV_IMG_DECLARE(ui_img_acoff_png);    // assets/acoff.png
LV_IMG_DECLARE(ui_img_acon_png);    // assets/acon.png
LV_IMG_DECLARE(ui_img_alarmarmedaway_png);    // assets/alarmarmedaway.png
LV_IMG_DECLARE(ui_img_alarmarmedhome_png);    // assets/alarmarmedhome.png
LV_IMG_DECLARE(ui_img_alarmdisarmed_png);    // assets/alarmdisarmed.png
LV_IMG_DECLARE(ui_img_alarmwarning_png);    // assets/alarmwarning.png
LV_IMG_DECLARE(ui_img_back_png);    // assets/back.png
LV_IMG_DECLARE(ui_img_background_png);    // assets/background.png
LV_IMG_DECLARE(ui_img_batterycharging_png);    // assets/batterycharging.png
LV_IMG_DECLARE(ui_img_batterynocharging_png);    // assets/batterynocharging.png
LV_IMG_DECLARE(ui_img_ceilingfanoff_png);    // assets/ceilingfanoff.png
LV_IMG_DECLARE(ui_img_ceilingfanon_png);    // assets/ceilingfanon.png
LV_IMG_DECLARE(ui_img_co2_png);    // assets/co2.png
LV_IMG_DECLARE(ui_img_coverclosed_png);    // assets/coverclosed.png
LV_IMG_DECLARE(ui_img_coveropen_png);    // assets/coveropen.png
LV_IMG_DECLARE(ui_img_curtainclosed_png);    // assets/curtainclosed.png
LV_IMG_DECLARE(ui_img_curtainopen_png);    // assets/curtainopen.png
LV_IMG_DECLARE(ui_img_display_png);    // assets/display.png
LV_IMG_DECLARE(ui_img_down_png);    // assets/down.png
LV_IMG_DECLARE(ui_img_ha_logo_png);    // assets/ha_logo.png
LV_IMG_DECLARE(ui_img_ha_logo32_png);    // assets/ha_logo32.png
LV_IMG_DECLARE(ui_img_high_light_png);    // assets/high_light.png
LV_IMG_DECLARE(ui_img_humidity_1_png);    // assets/humidity_1.png
LV_IMG_DECLARE(ui_img_humidity_2_png);    // assets/humidity_2.png
LV_IMG_DECLARE(ui_img_ic_co2_png);    // assets/ic_co2.png
LV_IMG_DECLARE(ui_img_ic_hum_png);    // assets/ic_hum.png
LV_IMG_DECLARE(ui_img_ic_switch1_off_png);    // assets/ic_switch1_off.png
LV_IMG_DECLARE(ui_img_ic_switch1_on_png);    // assets/ic_switch1_on.png
LV_IMG_DECLARE(ui_img_ic_switch2_off_png);    // assets/ic_switch2_off.png
LV_IMG_DECLARE(ui_img_ic_switch2_on_png);    // assets/ic_switch2_on.png
LV_IMG_DECLARE(ui_img_ic_temp_png);    // assets/ic_temp.png
LV_IMG_DECLARE(ui_img_ic_tvoc_png);    // assets/ic_tVOC.png
LV_IMG_DECLARE(ui_img_lightoff_png);    // assets/lightoff.png
LV_IMG_DECLARE(ui_img_lighton_png);    // assets/lighton.png
LV_IMG_DECLARE(ui_img_location_png);    // assets/location.png
LV_IMG_DECLARE(ui_img_location2_png);    // assets/location2.png
LV_IMG_DECLARE(ui_img_lock_png);    // assets/lock.png
LV_IMG_DECLARE(ui_img_low_light_png);    // assets/low_light.png
LV_IMG_DECLARE(ui_img_powerred_png);    // assets/powerred.png
LV_IMG_DECLARE(ui_img_setting_png);    // assets/setting.png
LV_IMG_DECLARE(ui_img_solargreen_png);    // assets/solargreen.png
LV_IMG_DECLARE(ui_img_temp_1_png);    // assets/temp_1.png
LV_IMG_DECLARE(ui_img_temp_2_png);    // assets/temp_2.png
LV_IMG_DECLARE(ui_img_time_png);    // assets/time.png
LV_IMG_DECLARE(ui_img_tvoc_png);    // assets/tvoc.png
LV_IMG_DECLARE(ui_img_up_png);    // assets/up.png
LV_IMG_DECLARE(ui_img_wifi_1_png);    // assets/wifi_1.png
LV_IMG_DECLARE(ui_img_wifi_2_png);    // assets/wifi_2.png
LV_IMG_DECLARE(ui_img_wifi_3_png);    // assets/wifi_3.png
LV_IMG_DECLARE(ui_img_wifi_disconet_png);    // assets/wifi_disconet.png
LV_IMG_DECLARE(ui_img_wifi_setting_png);    // assets/wifi_setting.png



LV_FONT_DECLARE(ui_font_font0);
LV_FONT_DECLARE(ui_font_font2);
LV_FONT_DECLARE(ui_font_font3);
LV_FONT_DECLARE(ui_font_font4);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
