// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: albetacom

#ifndef _ALBETACOM_UI_H
#define _ALBETACOM_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ha_alarm_keypad
void ui_ha_alarm_keypad_screen_init(void);
void ui_event_ha_alarm_keypad(lv_event_t * e);
extern lv_obj_t * ui_ha_alarm_keypad;
extern lv_obj_t * ui_ha_alarm_label;
extern lv_obj_t * ui_Container1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label3;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label4;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label5;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label6;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label7;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label8;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label9;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label11;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label10;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_LabelCode;
extern lv_obj_t * ui_LabelCode1;
// SCREEN: ui_ha_covers
void ui_ha_covers_screen_init(void);
void ui_event_ha_covers(lv_event_t * e);
extern lv_obj_t * ui_ha_covers;
extern lv_obj_t * ui_ha_covers_label;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_ImgButton1;
// SCREEN: ui_time
void ui_time_screen_init(void);
extern lv_obj_t * ui_time;
// SCREEN: ui_ha_alarm
void ui_ha_alarm_screen_init(void);
void ui_event_ha_alarm(lv_event_t * e);
extern lv_obj_t * ui_ha_alarm;
extern lv_obj_t * ui_ha_alarm_activation_label;
extern lv_obj_t * ui_ImgButton3;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_shutter_open_png);    // assets/shutter_open.png
LV_IMG_DECLARE(ui_img_shutter_png);    // assets/shutter.png
LV_IMG_DECLARE(ui_img_shield_lock_png);    // assets/shield_lock.png



LV_FONT_DECLARE(ui_font_font0);
LV_FONT_DECLARE(ui_font_font2);
LV_FONT_DECLARE(ui_font_font3);
LV_FONT_DECLARE(ui_font_font4);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
