// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: albetacom

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void AlarmCodeScreenLoadedAction(lv_event_t * e);
void Button1ClickedAction(lv_event_t * e);
void Button2ClickedAction(lv_event_t * e);
void Button3ClickedAction(lv_event_t * e);
void Button4ClickedAction(lv_event_t * e);
void Button5ClickedAction(lv_event_t * e);
void Button6ClickedAction(lv_event_t * e);
void Button7ClickedAction(lv_event_t * e);
void Button8ClickedAction(lv_event_t * e);
void Button9ClickedAction(lv_event_t * e);
void ButtonClearClickedAction(lv_event_t * e);
void Button0ClickedAction(lv_event_t * e);
void ButtonSendClickedAction(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
