// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: albetacom

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Button1ClickedAction(lv_event_t * e);
void ButtonClearClickedAction(lv_event_t * e);
void ButtonSendClickedAction(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
