// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: albetacom

#include "ui.h"

void Button1ClickedAction(lv_event_t * e)
{
	// Your code here
}

void ButtonClearClickedAction(lv_event_t * e)
{
	// Your code here
}

void ButtonSendClickedAction(lv_event_t * e)
{
	// Your code here
}

void Button2ClickedAction(lv_event_t * e)
{
	// Your code here
}

void Button3ClickedAction(lv_event_t * e)
{
	// Your code here
}

void Button4ClickedAction(lv_event_t * e)
{
	// Your code here
}

void Button5ClickedAction(lv_event_t * e)
{
	// Your code here
}

void Button6ClickedAction(lv_event_t * e)
{
	// Your code here
}

void Button7ClickedAction(lv_event_t * e)
{
	// Your code here
}

void Button8ClickedAction(lv_event_t * e)
{
	// Your code here
}

void Button9ClickedAction(lv_event_t * e)
{
	// Your code here
}

void Button0ClickedAction(lv_event_t * e)
{
	// Your code here
}
