// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: small

#include "ui.h"

void AlarmKeypadButton1Clicked(lv_event_t * e)
{
	// Your code here
}

void AlarmKeypadButton2Clicked(lv_event_t * e)
{
	// Your code here
}
