// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: albetacom

#include "../ui.h"

void ui_ha_energy_screen_init(void)
{
    ui_ha_energy = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ha_energy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ha_energy, lv_color_hex(0x1C1C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ha_energy, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_ha_energy);
    lv_bar_set_range(ui_Bar1, -2000, 5000);
    lv_obj_set_width(ui_Bar1, 531);
    lv_obj_set_height(ui_Bar1, 147);
    lv_obj_set_x(ui_Bar1, 5);
    lv_obj_set_y(ui_Bar1, -164);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ha_energy, ui_event_ha_energy, LV_EVENT_ALL, NULL);

}
