// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: albetacom

#include "../ui.h"

void ui_ha_ev_charge_screen_init(void)
{
    ui_ha_ev_charge = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ha_ev_charge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ha_ev_charge, lv_color_hex(0x1C1C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ha_ev_charge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_ha_ev_charge);
    lv_img_set_src(ui_Image1, &ui_img_teslamodel3_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 666
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 375
    lv_obj_set_x(ui_Image1, -44);
    lv_obj_set_y(ui_Image1, 116);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_ha_ev_charge);
    lv_img_set_src(ui_Image4, &ui_img_evcharger_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 473
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 527
    lv_obj_set_x(ui_Image4, 158);
    lv_obj_set_y(ui_Image4, 109);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 150);

    ui_Image2 = lv_img_create(ui_ha_ev_charge);
    lv_img_set_src(ui_Image2, &ui_img_batterynocharging_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 256
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 256
    lv_obj_set_x(ui_Image2, -100);
    lv_obj_set_y(ui_Image2, -130);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ha_ev_charge, ui_event_ha_ev_charge, LV_EVENT_ALL, NULL);

}
