// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: albetacom

#include "../ui.h"

void ui_ha_covers_screen_init(void)
{
    ui_ha_covers = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ha_covers, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ha_covers, lv_color_hex(0x1C1C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ha_covers, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ha_covers_label = lv_label_create(ui_ha_covers);
    lv_obj_set_width(ui_ha_covers_label, 476);
    lv_obj_set_height(ui_ha_covers_label, 17);
    lv_obj_set_x(ui_ha_covers_label, 0);
    lv_obj_set_y(ui_ha_covers_label, 4);
    lv_obj_set_align(ui_ha_covers_label, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_ha_covers_label, "Persianes");
    lv_obj_set_style_text_color(ui_ha_covers_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ha_covers_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ha_covers_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ha_covers_label, &ui_font_font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_ha_covers);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 290);
    lv_obj_set_height(ui_Slider1, 71);
    lv_obj_set_x(ui_Slider1, 11);
    lv_obj_set_y(ui_Slider1, 67);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);


    ui_ImgButton1 = lv_imgbtn_create(ui_ha_covers);
    lv_obj_set_width(ui_ImgButton1, 96);
    lv_obj_set_height(ui_ImgButton1, lv_pct(20));
    lv_obj_set_x(ui_ImgButton1, -131);
    lv_obj_set_y(ui_ImgButton1, -126);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ha_covers, ui_event_ha_covers, LV_EVENT_ALL, NULL);

}
