// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: albetacom

#include "../ui.h"

void ui_ha_alarm_screen_init(void)
{
    ui_ha_alarm = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ha_alarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ha_alarm, lv_color_hex(0x1C1C1C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ha_alarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ha_alarm_activation_label = lv_label_create(ui_ha_alarm);
    lv_obj_set_width(ui_ha_alarm_activation_label, 476);
    lv_obj_set_height(ui_ha_alarm_activation_label, 17);
    lv_obj_set_x(ui_ha_alarm_activation_label, 0);
    lv_obj_set_y(ui_ha_alarm_activation_label, 4);
    lv_obj_set_align(ui_ha_alarm_activation_label, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_ha_alarm_activation_label, "Alarma");
    lv_obj_set_style_text_color(ui_ha_alarm_activation_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ha_alarm_activation_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ha_alarm_activation_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ha_alarm_activation_label, &ui_font_font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton3 = lv_imgbtn_create(ui_ha_alarm);
    lv_obj_set_height(ui_ImgButton3, 64);
    lv_obj_set_width(ui_ImgButton3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_ImgButton3, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_ha_alarm, ui_event_ha_alarm, LV_EVENT_ALL, NULL);

}
