// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: albetacom

#include "../ui.h"

void ui_time_screen_init(void)
{
    ui_time = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_time, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


}
